services:
  mkas-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod
    container_name: mkas-app
    restart: unless-stopped
    networks:
      - default
    depends_on:
      mkas-mysql:
        condition: service_healthy

  mkas-web:
    image: nginx:alpine
    container_name: mkas-web
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - default
      - nginx-proxy
    depends_on:
      - mkas-app

  mkas-mysql:
    image: mysql:8.0
    container_name: mkas-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mkas_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mkas_mysqldata:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
  nginx-proxy:
    external: true

volumes:
  mkas_mysqldata:
    driver: local
